a = "mohak"
#print(len(a))
#b = 12
#s = str(b)
"""
print(s , type(s))
print(a[0], a[1], a[2], a[3], a[4])
print(ord(a[0]), ord(a[1]), ord(a[2]), ord(a[3]), ord(a[4]))
print(chr(109), chr(111), chr(104), chr(97), chr(107))
print(a.upper())
print(a.lower())
print(a.capitalize())
print(a.title())
print(a.isalpha())
print(a.isdigit())
print(a.startswith("m"))
print(a.endswith("k")) 
print(a.replace("m", "M"))
print(a.swapcase())
print(a.count("a"))
print(a.find("h"))
print(a.index("h"))
print(a.split("h"))
#print(a.replace("m", "G").split("h"))
#print(a.strip("m"))
#print(a.lstrip("m"))
#print(a.rstrip("k"))
print(a.islower())
print(a.isupper())
print(a.rindex("k"))
print(a.rfind("k"))
print(a.isalnum())
print(s.isdigit())
"""
print(a[0:3])
print(a[::-1])